/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('vexip-ui')['Button']
    Card: typeof import('vexip-ui')['Card']
    ConfigProvider: typeof import('vexip-ui')['ConfigProvider']
    Divider: typeof import('vexip-ui')['Divider']
    Form: typeof import('vexip-ui')['Form']
    FormItem: typeof import('vexip-ui')['FormItem']
    H1: typeof import('vexip-ui')['H1']
    Icon: typeof import('vexip-ui')['Icon']
    Input: typeof import('vexip-ui')['Input']
    Layout: typeof import('vexip-ui')['Layout']
    Linker: typeof import('vexip-ui')['Linker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('vexip-ui')['Row']
  }
}

// For TSX support
declare global {
  const Button: typeof import('vexip-ui')['Button']
  const Card: typeof import('vexip-ui')['Card']
  const ConfigProvider: typeof import('vexip-ui')['ConfigProvider']
  const Divider: typeof import('vexip-ui')['Divider']
  const Form: typeof import('vexip-ui')['Form']
  const FormItem: typeof import('vexip-ui')['FormItem']
  const H1: typeof import('vexip-ui')['H1']
  const Icon: typeof import('vexip-ui')['Icon']
  const Input: typeof import('vexip-ui')['Input']
  const Layout: typeof import('vexip-ui')['Layout']
  const Linker: typeof import('vexip-ui')['Linker']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Row: typeof import('vexip-ui')['Row']
}